name: Run tox

on: push

jobs:
  code-lint-test:
    name: tox tests
    runs-on: ubuntu-latest
    container: lisael/archtox

    steps:
      # Checkout the code which was pushed to Github
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Sets up Python 3.8
      # - name: Sets up Python 3.8
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.8

      # Install pylint and depdendencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      # Analyze all python scripts with pyline for static analysis
      # - name: Lint Code
      #   run: pylint `find . -type f | grep .py$ | xargs`

      # Runs Python Unit Tests
      - name: Test Code
        run: make test
